[env]
VCPKG_ROOT = { value = "ext/vcpkg", relative = true, force = true }
FFMPEG_DIR = { value = "ext/ffmpeg-n7.1.1-54-g6400860b9d-win64-gpl-shared-7.1", relative = true }
OPENSSL_NO_VENDOR = "1"
# PATH = { value = "target/release", relative = true }
